spring:
  profiles: dev12

configuration:
  dbConfig:
    host: jdbc:mysql://localhost:3306/falcon
    driver: com.mysql.cj.jdbc.Driver
    userId: root
    password: pass@123
    poolName: database-pool-${user.name}
